version: 2.1

orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2
  slack: circleci/slack@4.1

workflows:
  sample:
    jobs:
      steps:
        - node/test
        - heroku/deploy-via-git:
            requires:
              - node/test # only run deploy-via-git job if the build job has completed
            filters:
              branches:
                only: develop # Uncomment this line

