version: 2.1

orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2
  slack: circleci/slack@4.1

workflows:
  sample:
    jobs:
      - node/test
      - heroku/deploy-via-git:
          requires:
            - node/test # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: develop # Uncomment this line
          post-steps:
            - slack/notify:
                event: pass
                custom: |
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Farmhouse Thai Cuisine*\n:star::star::star::star: 1528 reviews\n They do have some vegan options, like the roti and curry, plus they have a ton of salad stuff and noodles can be ordered without meat!! They have something for everyone here"
                    },
                    "accessory": {
                      "type": "image",
                      "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/c7ed05m9lC2EmA3Aruue7A/o.jpg",
                      "alt_text": "alt text for image"
                    }
                  }
            - slack/notify:
                event: fail
                custom: |
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Farmhouse Thai Cuisine*\n:star::star::star::star: 1528 reviews\n They do have some vegan options, like the roti and curry, plus they have a ton of salad stuff and noodles can be ordered without meat!! They have something for everyone here failed"
                    },
                    "accessory": {
                      "type": "image",
                      "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/c7ed05m9lC2EmA3Aruue7A/o.jpg",
                      "alt_text": "alt text for image"
                    }
                  }
