version: 2.1

orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2
  slack: circleci/slack@4.1

workflows:
  sample:
    jobs:
      - node/test
      - heroku/deploy-via-git:
          requires:
            - node/test # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: develop # Uncomment this line
          post-steps:
            - slack/notify:
                event: pass
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "Hello, Assistant to the Regional Manager Dwight! *Michael Scott* wants to know where you'd like to take the Paper Company investors to dinner tonight.\n\n *Please select a restaurant:*"
                        }
                      }
                    ]
                  }
            - slack/notify:
                event: fail
                custom: |
                {
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "Hello, Assistant to the Regional Manager Dwight! *Michael Scott* wants to know where you'd like to take the Paper Company investors to dinner tonight.\n\n *Please select a fail:*"
                      }
                    }
                  ]
                }
